begin;

create table if not exists public.landing_content_versions (
  id bigint generated by default as identity primary key,
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists landing_content_versions_created_at_idx
  on public.landing_content_versions (created_at desc, id desc);

alter table public.landing_content_versions enable row level security;
revoke all on table public.landing_content_versions from anon, authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'landing-media',
  'landing-media',
  true,
  524288000,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif',
    'video/mp4',
    'video/webm',
    'text/vtt'
  ]::text[]
)
on conflict (id) do nothing;

commit;
